// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ehatnfiuoxlnjkrluysc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVoYXRuZml1b3hsbmprcmx1eXNjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMzOTgyMzQsImV4cCI6MjA2ODk3NDIzNH0.4IhdoBZwZmW4jNJlM9bj8cZmroGia7c9M15KgPQtE0w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});